### ISSUE TITLE
luma.oled installation failed

### ISSUE THREAD

**Issue by Galbi3000** [pangduckwai/PiDisplay#1]
Hi, I was following your guide as I just got one of these displays and the Waveshare site seems to be down but I ran into a roadblock at the luma.oled installation.

The last command to install the luma.oled driver produced an error:

`pi@raspberrypi:~ $ sudo -H pip install --upgrade luma.oled`
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support`
`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple`
`Collecting luma.oled`
`  Downloading luma.oled-3.5.0-py2.py3-none-any.whl (18 kB)`
`ERROR: Package 'luma.oled' requires a different Python: 2.7.13 not in '>=3.5, <4'`

I am new to Python stuff but I am guessing the current version of luma.oled requires Python 2.7 and the Raspberry Pi (Raspbian stretch version) has 3.5 installed. Any advice?

**Comment by Galbi3000** [comment]
I have fixed this issue. Even though luma.oled claims to work with Python 2.7 it requires Python 3+ to install but the Raspberry Pi defaults to 2.7 even though 3.5 (stretch) or 3.7 (buster) is installed.

The issue can be fixed by setting the Python alternatives which has not been done in Raspbian by default.
The following 2 commands will set Python 3 as default and include 2.7 as an alternative:
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1`
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 2`

If you are using Raspbian buster then change 3.5 to 3.7 in the second command.
Apparently in automatic mode it will chose the version of Python with the highest priority (the number 1 or 2 at the end of each command). You can manually select which version to use with the following command:
`sudo update-alternatives --config python`

Now the command to install luma.oled will work.

**Comment by pangduckwai** [comment]
Thanks for letting me know :)  sorry didn't notice your message until now
