### ISSUE TITLE
Kernel version?

### ISSUE THREAD

**Issue by spartan195** [pangduckwai/PiDisplay#6]
Greetings! 

I'm so happy I finally found someone with the same screen as mine explaining something. Seting up this thing is tedious.

I found a forum a while ago about why it doesn't work with the current kernel and the recommended one to use (under 4.9? I'm not sure...). I can't find it anymore, your repo is 4 years old I gues it was raspbian stretch. Do you remember which version of raspbian where you using?

[I'm using this](https://downloads.raspberrypi.org/raspbian/images/ ) to get old images, I could just download a random one from 2018 and test it but It would help me a lot if you remember it!

Thanks a bunch!

**Comment by spartan195** [comment]
Ok I figured it out.
The trickiest part was to install all requirements from the "official" documentation. But with you steps it's working fine.

Raspberry image: [2019-04-08-raspbian-stretch-lite](https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/)

I only get an error installing luma.oled, easy to fix by installing the especific version from pip by executing:
`sudo pip install -Iv luma.oled==2.7`

**Comment by pangduckwai** [comment]
Hello yeah it's been some times since I've played with my Pis...

Sorry I can't remember, also the computer i used back then crashed already.  I've just looked at my README, the raspbian version didn't seems to matter when I was writing it X)

I will try to bring the thing up tonight and check the version :)

**Comment by spartan195** [comment]
Confirmed working with [2019-04-09-raspbian-stretch](https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/)

I also edited the readme of my fork with the [install instructions](https://github.com/spartan195/PiDisplay/tree/xavi#prepare-raspbian) I end up using after some tries and reinstalls.

I really like the design you made!

**Comment by pangduckwai** [comment]
Hi good to hear it!  If you don't mind, maybe you can submit a pull request to update my instructions as well?

**Comment by spartan195** [comment]
I don't know how to do it, I never opened one. I'll look and submit one for you to check it out ;)

**Comment by pangduckwai** [comment]
Thanks :D
